### ISSUE TITLE
KeyError: '_module' when start run docker image

### ISSUE THREAD

**Issue by Kiara0107** [jamesread/prometheus-gmail-exporter#29]
Run the docker image failed with the following logging:

> Traceback (most recent call last):
>   File "/usr/local/sbin/gmail-exporter", line 266, in <module>
>     main()
>   File "/usr/local/sbin/gmail-exporter", line 236, in main
>     GMAIL_CLIENT = get_gmail_client()
>   File "/usr/local/sbin/gmail-exporter", line 223, in get_gmail_client
>     credentials = get_credentials()
>   File "/usr/local/sbin/gmail-exporter", line 46, in get_credentials
>     credentials = store.get()
>   File "/usr/lib/python3.10/site-packages/oauth2client/client.py", line 407, in get
>     return self.locked_get()
>   File "/usr/lib/python3.10/site-packages/oauth2client/file.py", line 54, in locked_get
>     credentials = client.Credentials.new_from_json(content)
>   File "/usr/lib/python3.10/site-packages/oauth2client/client.py", line 302, in new_from_json
>     module_name = data['_module']
> KeyError: '_module'

Wat can be the issue here?

**run command:**
```
docker run -d \
-v /etc/gmail/:/root/.prometheus-gmail-exporter/ \
--name gmail-exporter jamesread/prometheus-gmail-exporter:latest
```
where /etc/gmail/ contains the client_secret.json and login_cookie.dat.

- The login_cookie.dat is generated by running `python ./gmail-exporter.py` local
- Host is a Linux VM (Ubuntu 20.04.6)

**Comment by Kiara0107** [comment]
Unfortunately not. I removed the docker images from the ubuntu server and started all over. With running the same docker-run as before I get the same result:
```
Traceback (most recent call last):
  File "/usr/local/sbin/gmail-exporter", line 266, in <module>
    main()
  File "/usr/local/sbin/gmail-exporter", line 236, in main
    GMAIL_CLIENT = get_gmail_client()
  File "/usr/local/sbin/gmail-exporter", line 223, in get_gmail_client
    credentials = get_credentials()
  File "/usr/local/sbin/gmail-exporter", line 46, in get_credentials
    credentials = store.get()
  File "/usr/lib/python3.10/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/lib/python3.10/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/lib/python3.10/site-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'
```
